---
title: "Beta regression"
output: html_notebook
---

```{r}
data <- read.csv("./WindTurbineOutputPrediction-master/Task15_W_Zone1.csv")
names(data) <- c("zone_id", "timestamp", "p", "u10", "v10", "u100", "v100")

# Add wind speed and direction features
data$ws10 <- with(data, sqrt(u10^2 + v10^2))
data$dir10 <- with(data, atan(u10/v10))
data$ws100 <- with(data, sqrt(u100^2 + v100^2))
data$dir100 <- with(data, atan(u100/v100))
data <- na.omit(data)

# Partition into training and test data
train_length <- 8760L
train <- data[1:train_length,]
test <- tail(data, -train_length)
```

```{r}
#logistic function
logistc <- function(x){
  return(1/(1+exp(-x)))
}

loglike<-function(X,y,param){
rho<-exp(param[1])
beta<-param[2:length(param)]
lval<-0
for (i in 1:length(y))
{ eps<-0.0000000000001
  mu<-logistc(X[i,]%*%beta)
  lval<-lval-lbeta(eps+mu*rho,eps+(1-mu)*rho)+(mu*rho-1)*log(y[i])+((1-mu)*rho-1)*log(1-y[i])
}
return(lval)
}

dloglike<-function(X,y,param){
rho<-exp(param[1])
beta<-param[2:length(param)]
lval<-0
eps<-0.0000000000001
for (i in 1:length(y))
{ mui<-logistc(X[i,]%*%beta)
 dbeta<-X[i,]*as.vector((-rho*digamma(eps+mui*rho)+
                           rho*digamma(eps+(1-mui)*rho)+
                           rho*log(y[i]/(1-y[i])))*exp(-X[i,]%*%beta)/((1+exp(-X[i,]%*%beta))^2))
  drho<-(digamma(eps+rho)-mui*digamma(eps+rho*mui)-(1-mui)*digamma(eps+rho*(1-mui))+mui*log(y[i])+(1-mui)*log(1-y[i]))*rho
  lval<-lval+c(drho,dbeta)
}
return(lval)
}



loglike(matrix(1:3, nrow = 3, ncol = 2),c(0.5,0.1,0.9),c(1,1,2))
dloglike(matrix(1:3, nrow = 3, ncol = 2),c(0.5,0.1,0.9),c(1,1,2))
```



```{r}
n<-length(train$p)
X<-cbind(rep(1,n),train$ws10)
Xtest<-cbind(  rep(1,length(test$ws10)), test$ws10)
y<-(train$p*(n-1)+0.5)/n
fr <- function(param){
  #print(param)
  return(-loglike(X,y,param))
}
grr <- function(param){
  #print(param)
  return(-dloglike(X,y,param))
}
res<-optim(rep(1,ncol(X)+1), fr,grr, method = "L-BFGS-B",control=list(fnscale=-1))
param<-res$par
param[1]<-exp(param[1])
pred <-logistc(Xtest%*%param[2:length(param)])
MAE<-mean(abs(pred-test$p))
MAE
AIC<-2*length(res$par)-2*loglike(X,y,res$par)
AIC

```

```{r}
pdf("w10pred.pdf", width = 8)
plot(train$ws10, logistc(X%*%param[2:length(param)]),        xlab="Wind magnitude w10", ylab="Turbine power",
     cex.main=1.5, cex.lab=1.5, cex.axis=1.25)
points(train$ws10, train$p,col=rgb(255, 0, 0, max = 255, alpha = 55, names = "red50"))
dev.off()
```



```{r}
library(lubridate)
new_date=ymd_hm(train$timestamp)
months<-month(new_date)
hours<-hour(new_date)
#which(hours %in% c("02","03","04") )
Iwinter<-rep(0.0,length(new_date))
ind<-which(months %in% c(12,1,2) )
Iwinter[ind]=1.0
Ispring<-rep(0.0,length(new_date))
ind<-which(months %in% c(3,4,5) )
Ispring[ind]=1.0
Isummer<-rep(0.0,length(new_date))
ind<-which(months %in% c(6,7,8) )
Isummer[ind]=1.0
Ifall<-rep(0.0,length(new_date))
ind<-which(months %in% c(9,10,11) )
Ifall[ind]=1.0
Imorn<-rep(0.0,length(new_date))
ind<-which(hours %in% c(6,7,8,9,10,11) )
Imorn[ind]=1.0
Iafter<-rep(0.0,length(new_date))
ind<-which(months %in% c(12,13,14,15,16) )
Iafter[ind]=1.0
Ieven<-rep(0.0,length(new_date))
ind<-which(months %in% c(17,18,19,20,21,22) )
Ieven[ind]=1.0
Inight<-rep(0.0,length(new_date))
ind<-which(months %in% c(23,1,2,3,4,5) )
Inight[ind]=1.0
```



```{r}
n<-length(train$p)
X<-cbind(  Iwinter,Ispring,Isummer,Ifall,
          Iwinter*train$ws10,Ispring*train$ws10,Isummer*train$ws10,Ifall*train$ws10,
         Imorn,Iafter,Ieven,Inight,
          Imorn*train$ws10,Iafter*train$ws10,Ieven*train$ws10,Inight*train$ws10)
y<-(train$p*(n-1)+0.5)/n
fr <- function(param){
  #print(param)
  return(-loglike(X,y,param))
}
grr <- function(param){
  #print(param)
  return(-dloglike(X,y,param))
}
res<-optim(rep(1,ncol(X)+1), fr, grr, method = "L-BFGS-B")
param<-res$par
param[1]=exp(param[1])
Xtest<-cbind(  Iwinter,Ispring,Isummer,Ifall,
          Iwinter*test$ws10,Ispring*test$ws10,Isummer*test$ws10,Ifall*test$ws10,
         Imorn,Iafter,Ieven,Inight,
          Imorn*test$ws10,Iafter*test$ws10,Ieven*test$ws10,Inight*test$ws10)
pred <-logistc(Xtest%*%param[2:length(param)])
MAE<-mean(abs(pred-test$p))
MAE
AIC<-2*length(res$par)-2*loglike(X,y,res$par)
AIC
```

```{r}
plot(train$ws10, logistc(X%*%param[2:length(param)]),        xlab="Wind magnitude w10", ylab="Turbine power",
     cex.main=1.5, cex.lab=1.5, cex.axis=1.25)
points(train$ws10, train$p,col=rgb(255, 0, 0, max = 255, alpha = 55, names = "red50"))
```
```{r}
n<-length(train$p)
X<-cbind(  rep(1,length(train$ws10)), train$ws10,train$ws100,train$dir100)
Xtest<-cbind(  rep(1,length(test$ws10)), test$ws10,test$ws100,test$dir100)
y<-(train$p*(n-1)+0.5)/n
fr <- function(param){
  #print(param)
  return(-loglike(X,y,param))
}
grr <- function(param){
  #print(param)
  return(-dloglike(X,y,param))
}
res<-optim(rep(1,ncol(X)+1), fr, grr, method = "L-BFGS-B")
param<-res$par
param[1]=exp(param[1])
pred <-logistc(Xtest%*%param[2:length(param)])
MAE<-mean(abs(pred-test$p))
MAE
AIC<-2*length(res$par)-2*loglike(X,y,res$par)
AIC
```
```{r}
plot(train$ws10, logistc(X%*%param[2:length(param)]),        xlab="Wind magnitude w10", ylab="Turbine power",
     cex.main=1.5, cex.lab=1.5, cex.axis=1.25)
points(train$ws10, train$p,col=rgb(255, 0, 0, max = 255, alpha = 55, names = "red50"))
```

